### ISSUE TITLE
Crossbeam

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#107]
Implement crossbeam channels.

**Comment by TimonPost** [comment]
As this graph shows, crossbeam is a lot faster. I think we should give it a try.,
https://camo.githubusercontent.com/424c50d0e756b9ba098ef4cc60c5f348ce08602b/68747470733a2f2f692e696d6775722e636f6d2f4b7732645163792e706e67

**Comment by LucioFranco** [comment]
@TimonPost if you want to use it I'm fine with it, but I would like to see benchmarks that PROVE it is better in our use case. 😄

**Comment by TimonPost** [comment]
We use crossbeam channel since #138
