### ISSUE TITLE
Investigate the use of a `Vec` for the buffer

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#141]
A `Vec` here is not really the correct use case for it since we do not need the features of dynamically sized array of bytes. A couple of options are available:

- Stick with `Vec`
- Use slices `[u8]`
- Use [Bytes](https://docs.rs/bytes/0.4.11/bytes/) which is a networking programming

**Comment by TimonPost** [comment]
A Vec `here` is not really correct, can you elaborate on 'here'?

**Comment by LucioFranco** [comment]
Ah totally sorry, in #138 there was a change that uses a `Vec` as the buffer for the socket. This is just to open a discussion on what we should think about using.

**Comment by TimonPost** [comment]
Alright, my upcoming PR will fix this.

**Comment by TimonPost** [comment]
I belive this is fixed
