### ISSUE TITLE
Refine public `Socket` API

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#142]
_note: this comment is in reference to https://github.com/amethyst/laminar/pull/138#discussion_r254951048_

We should probably move these to some sort of `Socket` and `SocketHandle` where `SocketHandle` is clonable and provides the send and recv interface.  This would then allow you to use `Socket` to drive the inner transport and the `SocketHandle` to read and write. That should clean this up. `Socket` should still provide the read and write interface but is not clonable.

This is what Im thinking

```rust
struct Socket {
	fn send(&mut self, packet: Packet) -> Result<()>;
	fn recv(&mut self) -> Packet;
	fn start_polling(&mut self) -> Result<()>;
}

#[derive(Clone)]
struct SocketHandle {
	fn send(&mut self, packet: Packet) -> Result<()>;
	fn recv(&mut self) -> Packet;
}
```

cc @fhaynes @TimonPost @jstnlef

**Comment by TimonPost** [comment]
Let's close this for now. I think it is longer relevant for our current project.
