### ISSUE TITLE
Investigate poor performance on Windows VMs

### ISSUE THREAD

**Issue by jstnlef** [amethyst/laminar#157]
Recently, as part of a move to simplify our use of external dependencies, made some changes to move back to Rust's standard library sockets + threads. However, the test cases on travis.ci, specifically the Windows builds, were timing out and failing the build. This was, naturally, unexpected and we should really dig into why this is happening.

**Comment by TimonPost** [comment]
We did find out that sleeping a thread can make the CI run for a longer period than what is normal. This has partially to do with how windows sleep. We managed, by implementing our own sleeping, to reduce the CI running time

**Comment by TimonPost** [comment]
This isn't realy a problem anymore right? Or do we still encounter errors with this? This can be closed for now, because it seems it has not urgent.
