### ISSUE TITLE
Virtual Connection gets dropped with reliable ordered

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#184]
So, I am seeing that a reliable order stops working after some time. I tried to track this down and see the origin. I will continue to do so.

Running this code with server and client will result in the server to not get any events after a certain amount of time.

_code I am using to test reliable ordered_
```rust
//! Note that the terms "client" and "server" here are purely what we logically associate with them.
//! Technically, they both work the same.
//! Note that in practice you don't want to implement a chat client using UDP.
extern crate laminar;

use std::io::stdin;

use laminar::{Config, ErrorKind, Packet, Socket, SocketEvent};
use std::thread;
use std::time::Duration;
use std::io::Write;

const SERVER: &str = "127.0.0.1:12351";

fn server() -> Result<(), ErrorKind> {
    let mut packet_receive_counter = 0;

    let mut config = Config::default();
    config.socket_polling_timeout = None;
    config.socket_event_buffer_size = 10000;

    let (mut socket, packet_sender, event_receiver) = Socket::bind_with_config(SERVER, config)?;
    let _thread = thread::spawn(move || socket.start_polling());

    println!("Listening for connections to {}", SERVER);

    let mut last_received = 0;
    loop {
        match event_receiver.recv().expect("Should get a message") {
            SocketEvent::Packet(packet) => {
                let msg = packet.payload();

                let packet_nmr = String::from_utf8_lossy(msg).parse::<i32>().unwrap();

                if last_received != packet_nmr {
                    panic!("Should not happen {}", packet_nmr)
                }

                println!("{}", last_received);
                last_received += 1;
            }
            SocketEvent::Timeout(address) => {
                println!("Client timed out: {}", address);
            }
            _ => {}
        }
    }

    Ok(())
}

fn client() -> Result<(), ErrorKind> {
    let addr = "127.0.0.1:12352";

    let mut config = Config::default();
    config.socket_polling_timeout = None;
    config.socket_event_buffer_size = 10000;

    let (mut socket, packet_sender, event_receiver) = Socket::bind_with_config(addr, config)?;
    println!("Connected on {}", addr);
    let _thread = thread::spawn(move || socket.start_polling());

    let server = SERVER.parse().unwrap();

    let mut s_buffer = String::from("test string");

    for i in 0..1_0000 {
        packet_sender
            .send(Packet::reliable_ordered(
                server,
                i.to_string().into_bytes(),
                None
            ))
            .unwrap();
        thread::sleep(Duration::from_millis(3));
//        println!("Send packet {}\n", i);
    }

    Ok(())
}

fn main() -> Result<(), ErrorKind> {
    let stdin = stdin();

    println!("Please type in `server` or `client`.");

    let mut s = String::new();
    stdin.read_line(&mut s)?;

    if s.starts_with("s") {
        println!("Starting server..");
        server()
    } else {
        println!("Starting client..");
        client()
    }
}

```

The ordering stream[ keeps track](https://github.com/amethyst/laminar/blob/master/src/infrastructure/arranging/ordering.rs#L245) of the incoming packet id. This id changes all of the sudden to 1 and detects that the `incomming_offset` < `expected_index`, this is not possible in the case of reliable order because we acknowledge each packet. So that packet is thrown away [here](https://github.com/amethyst/laminar/blob/master/src/infrastructure/arranging/ordering.rs#L251). 

Task:

Find out why the incoming index becomes 1 after some time, while the expected is `n`.

_capture of the raw packet, as you can see there is some weird stuff going on there_
![Naamloos](https://user-images.githubusercontent.com/19969910/57483640-8fd95280-72a7-11e9-9d24-fd0bfb9280ad.png)

**Comment by jstnlef** [comment]
So while I'm unsure what the issue with it could be, I can say that if both your client and server aren't sending AND receiving messages, no acking is occurring.

**Comment by TimonPost** [comment]
The server receives and the client sends, this isn't the problem. The real problem is the ordering id to specify the order of a packet in a stream which all of the sudden changes to 1 again. I think it won't be that hard to track down why that is, it already is for a great part. I'll invest some time into this one.

**Comment by TimonPost** [comment]
Alright, I have one clue, the client drops after a certain amount of time which causes all client data to be destroyed including the arranging streams and the information of the ordering id. When the next packet arrives it starts obviously at one for that client.

Next question why does the client drop.

**Comment by TimonPost** [comment]
Ah, I discovered it. 

If a client sends a packet it [inserts](https://github.com/amethyst/laminar/blob/master/src/net/socket.rs#L104) a `VirtualConnection` for itself, when doing this and the server does not return any packets, the client will basicly remove himself because he is idling, or at least not receiving anything. 

However, we do store acknowledgment information, ordering information etc of this client in this `VirtualConnection` instance. In case of ordering, after the removal of this `VirtualConnection`, and the client sends another packet, the order id starts at 1 again because it inserted a fresh new `VirtualConnection` for itself. But the server, with which the client is connected still has it's own `VirtualConnection`, because of that some information might get misinterpreted.

A solution could be to specify if a client can idl with a boolean, this prevents the client from removing himself.

**Comment by jstnlef** [comment]
There is a configuration option that allows you to lengthen the time a client can be idle before a timeout. However, in general, we don't want a client to be idling. In order for the protocol to work correctly, we need both the client and the server to be sending messages at a consistent rate.

**Comment by TimonPost** [comment]
It is true that in a 'normal' FPS situation the server and clients wouldn't have this problem. If we just go with this fact that people should always actively send packets in two ways some people only using one packet flow to a server won't be able to use our protocol. Shouldn't we just add this functionality, it is just a few lines of code.

**Comment by jstnlef** [comment]
Well, it's not quite a couple of lines of code. For example, if the server never sends any messages back there's no way to guarantee reliability. So in order to properly ensure reliability, we would need to have our protocol send an ack message whenever it received a message or something to that affect.

**Comment by TimonPost** [comment]
Ahh, your right, I didn't think of that part yet. Hrrmmm, yes that would be a big change. Maybe it would be useful to add that to our readme to avoid misconception of our protocol.

**Comment by OvermindDL1** [comment]
Raknet had a required heartbeat every 1 or 5 or so seconds, it was normally attached to the same frame as other packets but would be sent on its own if nothing was being sent or received.  It was just for these purposes.

**Comment by jstnlef** [comment]
That's definitely a way to solve it 👍

**Comment by BourgondAries** [comment]
https://github.com/amethyst/laminar/pull/199 might be related.

**Comment by TimonPost** [comment]
Yes, it is related when VirtualConnection drops all client related data with it goes away as well.

**Comment by TimonPost** [comment]
Because the user is responsible to keep a connection open, this can be closed.
