### ISSUE TITLE
Potentially useless Linux executable included in repository

### ISSUE THREAD

**Issue by NGgmnBQGwR** [amethyst/laminar#185]
Commit 28ef8ee782c38c1480e2c68e42040a52ca4a267d included this 46.6MB file: https://github.com/amethyst/laminar/blob/28ef8ee782c38c1480e2c68e42040a52ca4a267d/core, which looks to be a Linux GDB executable.
It's not referenced anywhere, including the pull request which added it (https://github.com/amethyst/laminar/pull/160), so I assume it was added by mistake.

**Comment by LucioFranco** [comment]
@TimonPost this looks like it was something you added? I think this probably can be removed.

**Comment by TimonPost** [comment]
This is removed in #219
