### ISSUE TITLE
Excessive CPU usage in "start_polling" method

### ISSUE THREAD

**Issue by NGgmnBQGwR** [amethyst/laminar#186]
Using the following:

```
>rustup show
Default host: x86_64-pc-windows-gnu

stable-x86_64-pc-windows-gnu (default)
rustc 1.34.2 (6c2484dc3 2019-05-13)
```

```
>rustc -V
rustc 1.34.2 (6c2484dc3 2019-05-13)
```

```
>git rev-parse HEAD
38e129ae39ab001bad48083e3e0e98a89326fc1a
```

```
>cargo run --release --example server_client
    Finished release [optimized] target(s) in 0.10s
     Running `target\release\examples\server_client.exe`
Please type in `server` or `client`.
s
```

After which the polling thread takes the entire CPU core to himself:
![image](https://user-images.githubusercontent.com/4226721/58190729-53feae00-7ce7-11e9-9c8b-dfe461491002.png)

Which, to my limited understanding of networking, should not happen.

And possibly related - the "socket_polling_timeout" field in Config struct isn't used anywhere since its only usage was removed from "start_polling" in f2aa9e60405ad27937c71a84918f04272aa52805.

**Comment by jstnlef** [comment]
I admit that the polling loop is a bit aggressive currently. Originally, to support nonblocking reads and writes to the underlying socket, we were using mio. However, we noticed that performance of mio on windows wasn't where we'd like it to be so we swapped it out to use a standard library socket in nonblocking mode. There's work to be done here to make it less abusive.

**Comment by BourgondAries** [comment]
One could provide a duration to sleep between each loop.

**Comment by TimonPost** [comment]
Related #191

**Comment by TimonPost** [comment]
Now we have a `manual_poll ` function, I believe this issue can be closed.
