### ISSUE TITLE
Suggestion: Put Sender and Receiver inside Socket

### ISSUE THREAD

**Issue by Ploppz** [amethyst/laminar#195]
Then let all functions of `Sender` and `Receiver` such as `send()` and `recv()` be function of `Socket`. This should simplify the interface, and make the user not have to pass around 3 different values to use the socket.

**Comment by BourgondAries** [comment]
This can be implemented but will likely be a breaking change... Ideally remove the looping thing altogether and let the user loop if he so desires.

**Comment by TimonPost** [comment]
Removing the looping is an option, the downside of that is that we need to have changes to the API when we do want to use MIO again.

**Comment by Ploppz** [comment]
I don't see how looping is relevant to this issue.

**Comment by BourgondAries** [comment]
@Ploppz, we can potentially also make it even faster by making `manual_poll` use a queue instead of a thread-safe queue.

**Comment by jstnlef** [comment]
I think packaging the return values into a single socket(like) wrapper struct would improve the ergonomics quite a bit.

**Comment by BourgondAries** [comment]
This can be closed.
