### ISSUE TITLE
Move TCP Connections to use a pool similar to the UDP one

### ISSUE THREAD

**Issue by fhaynes** [amethyst/laminar#24]

**Comment by fhaynes** [comment]
So one option for this to provide a Trait that abstracts VirtualConnections and TCPConnections. Something like:
```rust
pub enum ConnectionProtocol {
    AmethystUDP,
    TCP
}

pub trait Connection {
    fn get_protocol_type(&self) -> ConnectionProtocol;
    fn send_reliable(&self);
    fn send_unreliable(&self);
}
```

**Comment by fhaynes** [comment]
Another option is we expand the ConnectionPool struct to have two separate collections: one for UDP, one for TCP, such as:
pub struct ConnectionPool
{
    timeout: Duration,
    connections: ConnectionsCollection,
    tcp_connections: TcpConnectionsCollection,
    sleepy_time: Duration,
    poll_interval: Duration,
}

**Comment by TimonPost** [comment]
We could also make an trait for `ConnectionPool` so we can create an TcpConnectionPool and an UdpConnectionPool.

**Comment by TimonPost** [comment]
We are removing TCP from the lib see PR #56
