### ISSUE TITLE
last_heard not being updated in VirtualConnection

### ISSUE THREAD

**Issue by fhaynes** [amethyst/laminar#25]

**Comment by fhaynes** [comment]
And, well, it should be updated. =)

**Comment by TimonPost** [comment]
I have created a fix for it. But it will probably not be meregd withing two weakes It is a small tweak so if anyone does an PR you could add this line to the `process_received()` in `SocketState`.

**Comment by TimonPost** [comment]
Sorry, accidentally closed issue :)

**Comment by TimonPost** [comment]
Sorry, accidentally closed issue :)

**Comment by fhaynes** [comment]
I'll take care of it
