### ISSUE TITLE
Add option to compress messages

### ISSUE THREAD

**Issue by maniyar1** [amethyst/laminar#274]
I'm still new to the codebase, so let me know if I misrepresent something...

I was curious whether an option to compress packets would be useful? Looking at #225, I was wondering if compressing could help avoid fragmentation where it would otherwise be needed.
As far as algorithms I don't know what would be best; [quake 3 used per-packet Huffman compression](https://web.archive.org/web/20190416203531/http://trac.bookofhook.com/bookofhook/trac.cgi/wiki/Quake3Networking#CompressionEncryptionandPackets). We could also use gzip I guess, or implement multiple algorithms and let the user choose. I'm not really that informed about compression algorithms.
Let me know if this is something that would be useful and I can try my hand at implementing it.

**Comment by brandonlamb** [comment]
Hello!

My understanding is that when it comes to building multiplayer netcode, you really want to hand pack your packets for optimal size, or use something like google protocol buffers.

Is the context for something like Huffman coding for string values?

**Comment by maniyar1** [comment]
That could be one application...now that I've played with everything a bit more I imagine this isn't really something that needs to be in the library, it can be something the user does themselves. The quake 3 example is...valid but quake 3 has a very unique network setup. I think I'll end up closing the issue soon
