### ISSUE TITLE
Adding Congestion avoidance

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#3]
**Promblem**
If we send just packets without caring about the inernet speed of the client we can flood the network. Since the router tries to deliver all packages it buffes up all packets in chache. We do not want the router to buffer up packets instead it should drop them. We need to try to avoid sending too much bandwidth in the first place, and then if we detect congestion, we attempt to back off and send even less.

**Solution**
At first we need to measure roundtrip time [RTT](https://en.wikipedia.org/wiki/Round-trip_delay_time)

How to implement it [see](https://gafferongames.com/post/reliability_ordering_and_congestion_avoidance_over_udp/):

- For each packet we send, we add an entry to a queue containing the sequence number of the packet and the time it was sent.

- Each time we receive an ack, we look up this entry and note the difference in local time between the time we receive the ack, and the time we sent the packet. This is the RTT time for that packet.

- Because the arrival of packets varies with network jitter, we need to smooth this value to provide something meaningful, so each time we obtain a new RTT we move a percentage of the distance between our current RTT and the packet RTT. 10% seems to work well for me in practice. This is called an exponentially smoothed moving average, and it has the effect of smoothing out noise in the RTT with a low pass filter.

- To ensure that the sent queue doesn’t grow forever, we discard packets once they have exceeded some maximum expected RTT. As discussed in the previous section on reliability, it is exceptionally likely that any packet not acked within a second was lost, so one second is a good value for this maximum RTT.

_Two network conditions:_
I think the easies one is that we have two types of network conditions: **Good**, **Bad**. If connection is **good** we send packets at a rate for example 30 p/s if the connection is **bad** drop down to 10 p/s (depents on packet size)

How do you switch between good and bad? The algorithm I like to use operates as follows:

- If you are currently in good mode, and conditions become bad, immediately drop to bad mode

- If you are in bad mode, and conditions have been good for a specific length of time ’t’, then return to good mode

- To avoid rapid toggling between good and bad mode, if you drop from good mode to bad in under 10 seconds, double the amount of time ’t’ before bad mode goes back to good. Clamp this at some maximum, say 60 seconds.

- To avoid punishing good connections when they have short periods of bad behavior, for each 10 seconds the connection is in good mode, halve the time ’t’ before bad mode goes back to good. Clamp this at some minimum like 1 second.

And if that is workig we can even detect if we can send more packets if the connection is good but we should be carfull with this. So first let get the base implementation.

**Comment by TimonPost** [comment]
We now have an calculation for the round trip time. See #30 for more details.

**Comment by lain-dono** [comment]
I think you should consider [RFC5348](https://tools.ietf.org/html/rfc5348). But it looks complicated.

**Comment by TimonPost** [comment]
True, I'll do some investigation thanks!

**Comment by TimonPost** [comment]
For now, I think this is not relevant anymore. Congestion avoidance will be done at a higher level like `amethyst_network` as discussed. Reopen if you don't' agree.

**Comment by sillyousu** [comment]
hi @TimonPost  
Are there a issues tracking `congestion avoidance` in amethyst repository?

**Comment by TimonPost** [comment]
No there aren't.
