### ISSUE TITLE
Adding unique protocol id

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#4]
**Problem**

Imagine we have multiple version of this protocol someone is using for the first version and the for the server an old version. This could go wrong since we might have changed the packet content in newer versions. 

**Solution**
We could include some crc32 code in the packet this crc32 code is some encode version of the version number or something like that. The crc32 encoded string will be encoded with the version id / protocol version. This way we can identify if the two packets are from the same server/client version. If the packet is not matching the server version it will be dropped each packet should have some unique protocol id

**Comment by LucioFranco** [comment]
@TimonPost are you planning on doing this one? If so please assign it to yourself so that someone else doesn't go and do it 😄

**Comment by TimonPost** [comment]
eagleness was working on that If I where right.

**Comment by TimonPost** [comment]
See #55
