### ISSUE TITLE
Guidelines, overal crate improvements.

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#45]
Here are a couple of things I think who are important for a library like this one. If you see something lac of these issues feel free to open a PR. When I read some code from other libs like this one, but in C++/C I saw that there was a huge shortcoming on most of the following points. Which makes the code difficult to read and understand.

- Every type, method and some fields should be commented.
- Calculations should be documented. Whether it would be in a PR or code. But it must be clear what is done. 
- Don't hard code values. We should only use config, consts etc hardcoded values are the root of all evil.
- Everything should be tested, so feel free to write tests.
- Documentation.
- Keep files small better have small files with small pieces of logic than having one file with 1000 lines of logic with multiple types/structs etc. Note that I speak of logic, tests not included.
- Absolutely no panics/unwraps in the logic we need to have propper error handling. You may have panics/unwraps in test code.
- Grammar / English improvement. I am not a native English speaker so forgive me when making some mistakes. I am trying to avoid making them in the first place. But some checks could not be wrong.

**Comment by Xaeroxe** [comment]
Over on the main Amethyst repo we implemented a different approach, which was to use warnings most of the time except for on CI, where we added flags to cargo to deny on warnings.  This allows you to prototype quickly, but still quality gates the repo.  See https://github.com/amethyst/amethyst/pull/1011 and https://github.com/amethyst/amethyst/pull/1025 for more.

**Comment by LucioFranco** [comment]
@Xaeroxe I like this approach. And we should be following what amethyst/amethyst does anyways since we are another repo under the same org.

**Comment by CBenoit** [comment]
Maybe we should add rustfmt verification in CI to make sure formatting is uniform.

**Comment by LucioFranco** [comment]
@CBenoit yes, this is the plan. Mostly all of the amethyst crates are waiting for `rustfmt` to `1.0` to formalize that. They are like a month overdue 😄

**Comment by LucioFranco** [comment]
punting this to `0.2.0`

**Comment by fhaynes** [comment]
I'm going to try to add code coverage for 0.1.0 as part of this.

**Comment by TimonPost** [comment]
Isn't really needed I think. We could better put something like this in /docs. Which it already does over here: https://github.com/amethyst/laminar/blob/master/docs/CONTRIBUTING.md
