### ISSUE TITLE
Module inception in project architecture

### ISSUE THREAD

**Issue by CBenoit** [amethyst/laminar#60]
There are currently some modules that have the same name as their parent module (https://github.com/amethyst/laminar/blob/master/src/packet/packet.rs and https://github.com/amethyst/laminar/blob/master/src/sequence_buffer/sequence_buffer.rs).
This is linted by this clippy warning: https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#module_inception

Maybe we should move content of `packet.rs` in `packet/mod.rs` and content of `sequence_buffer.rs` in `sequence_buffer/mod.rs`.
This wouldn't even change imports as `pub use` are already used:
https://github.com/amethyst/laminar/blob/master/src/packet/mod.rs#L12

This isn't a critical issue and can be ignored if you prefer another sub-module + pub use.

**Comment by TimonPost** [comment]
I get your point but I am not entirely sure of I want to move the logic to the mod.rs most of the time if I brouwse trough rust files I am trying to find that one type I expected it to be. Finally I find it in the mod.rs. For me it is not convenient to to have logic the module file. I like to keep it for imports management only for most cases.

**Comment by CBenoit** [comment]
It's ok! I just wanted to make sure that was intended :+1:

**Comment by fhaynes** [comment]
Closing as everyone seems to be in agreement here. =)
