### ISSUE TITLE
Add variable naming conventions to style guide doc

### ISSUE THREAD

**Issue by fhaynes** [amethyst/laminar#66]

**Comment by fhaynes** [comment]
This is important because as we grow, we can't have PRs held up for days due to someone thinking a variable name is too short. We need to codify these rules and write linters for the ones we can. Preferably we then use them as pre-commit thingies (that's a technical term).

**Comment by fhaynes** [comment]
Hooks! That's what I meant. Pre-commit hooks.

**Comment by LucioFranco** [comment]
I don't think variable names are in the scope of a linter personally. I would like to follow clippy guidelines and rustfmt guidelines as well.

**Comment by fhaynes** [comment]
Not variable names, variable length. What can be automated should be automated, and if part of the style guideline is "no single letter variable names", then that should be an automatic linter. Variable names are too contextual to easily automate.

**Comment by fhaynes** [comment]
And following clippy and rustfmt guidelines is fine, but I don't think they would have flagged the things you did? In which case we need another way to detect them, or we have to stop worrying about them.

**Comment by LucioFranco** [comment]
Closing this as naming guidelines should follow regular rust patterns. That is snake_case and descriptive.
