### ISSUE TITLE
Enable deny attributes

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#72]
This issue is to track the progress of denying warnings / missing docs.

- [ ] deny warnings on CI
- [ ] warn for missing docs on public interfaces

**Comment by torkleyy** [comment]
Partial duplicate of #80

**Comment by torkleyy** [comment]
Copy from #80

I recommend enabling a warning instead and denying all warnings on CI, similar to what we've done in the Amethyst main repository.

**Comment by torkleyy** [comment]
## Task

Amethyst uses a bot called bors to merge its PRs safely. For that, the branch gets merged with `master` into another branch and is tested separately by Travis. We want that this test fails if warnings are enabled. You can look up in amethyst/amethyst how this can be done.

Please make sure we still can compile code without docs locally. It should only stop us from merging such code into master.

**Comment by TimonPost** [comment]
See: #90

**Comment by LucioFranco** [comment]
Lets keep this open until that PR gets merged at least
