### ISSUE TITLE
Review library level exports  and public API.

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#75]
Right now, it seems that we export almost everything in the crate publically at the library level. I would like to go through and review these to make sure we want to expose it or not. If we do, we need it to be documented.

Since we are coming close to version 0.1.0 I want to have some thought about how the public API should look and what the user should not be seeing. Please leave suggestions. Once we agree we update that into the main issue description.

**Comment by TimonPost** [comment]
```
// re-exports
use laminar::{UdpSocket, NetworkConfig, Event, ProtocolVersion, DeliveryMethod, Packet};
use laminar::net::{UdpSocket, NetworkConfig};
use laminar::error::{NetworkErrorKind, NetworkResult}

// original namespaces should also be availibe instad of re-export.
use laminar::packet::Packet;
use laminar::infrastructure::DeliveryMethod;
use laminar::event::Event;
```
