### ISSUE TITLE
Add attribute to deny missing documentation for public interfaces.

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#80]
https://doc.rust-lang.org/1.9.0/book/documentation.html#missing-documentation

**Comment by torkleyy** [comment]
I recommend enabling a warning instead and denying all warnings on CI, similar to what we've done in the Amethyst main repository.

**Comment by LucioFranco** [comment]
@torkleyy sure, I like that approach.

**Comment by LucioFranco** [comment]
actually closing this in favor of #72
